### ISSUE TITLE
Use parallel code to https://github.com/ga-wdi-boston/js-xml-http-request?

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/node-http-client#2]
@jrhorn424: I wrote this after the existing example code:  https://gist.github.com/gaand/a75a2b0485d78fdd8ee1

**Comment by jrhorn424** [comment]
Oh, I like it! The sign-up then sign-in thing really resonated with them.

**Comment by gaand** [comment]
Close with 9d58342415080fc8302885818765a2b141d30c51
